### ISSUE TITLE
Are you still interested in contributions? 

### ISSUE THREAD

**Issue by ole108** [oleiade/gomme#8]
I'm looking for a parser combinator library for a little DSL. 
I will need better error handling and a few other things. 
Fortunately I can build all of it myself.  😀
I just want to know if you are interested in such contributions. 
Otherwise I will happily fork your repo and go my own way.

**Comment by oleiade** [comment]
Hi @ole108 👋🏻 

I'd be interested in receiving contributions indeed 👍🏻 I still use this library quite a lot, but I got probably too used to its quirks and limitations to be objective, so this would be very much welcome! 

Please feel free to open dedicated issues for the stuff you'd like to add/fix/improve, and let's get this ball rolling 🙇🏻

**Comment by ole108** [comment]
Hi @oleiade ,

I have forked the repo by now and build a lot of changes into it.
It is all done to allow much better error handling (which is still missing).
The following changes are the biggest:

- You use a generic type for the input (`[]byte | string`).
  Unfortunately you can't easily read real runes from this kind of input.
  In all of your code you are really reading bytes and sometimes convert them to a rune.
  This will never allow you to handle real multi-byte runes (> 255).
  I switched to pure []byte internally and using the Go `utf8` package to handle strings.
  This way I can support full Unicode which is necessary for my project.
- I switched the parsers from an Input+Result model to a State+Output model.
  This will make some error handling easier and now only the Output needs to be generic.
  This looks very clean. And I am using better encapsulation now (unexported fields, ...).
- I moved all the parsers to a sub-package.
  This ensures that the don't touch any internal state.
  And shows users that they can easily add any kind of parser themselves.

You are invited to take a look at it here:
[ole108/parcomb](https://github.com/ole108/parcomb)

I would be happy to open a pull request if you like it.
If it's too different for you, I will understand.
I am currently adding some nice things from `goparsify`.
I hope you like it. :)

Cheers,
Ole

**Comment by ole108** [comment]
Hi @oleiade ,
I would love to get some feedback from you.
I tried to keep the user experience as similar as possible.

If you don't respond soon (by Monday evening), I will finally fork it to my own organization and change the name.
I will be happy to reference `gomme` of course.
Especially for people who don't need error recovery.
You might want to add the error reporting to `gomme`.
That is rather simple and helps a lot already. You just get only 1 error per run.

Best,
Ole

**Comment by ole108** [comment]
I still need a bit more time to fix some bugs.
Will do a PR after that.
That will give you a chance to consider.
